blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
    path('posts/', include("posts.urls", namespace="posts"))
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

posts/urls.py
from django.urls import path, include
from posts import views

app_name = "posts"

urlpatterns = [
    path("create/", views.create_post, name = "create_post"),
    path("my-posts/", views.my_posts, name = "my_posts"),
    path("delete/<int:id>/", views.delete_post, name = "delete_post"),
    path("edit/<int:id>/", views.edit_post, name = "edit_post"),
    path("draft/<int:id>/", views.draft_post, name = "draft_post"),
    path("<int:id>/", views.post, name = "post"),
]

web/urls.py
from django.urls import path, include
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:id>/", views.post, name = "post"),
]

posts/models.py
from django.db import models
from ckeditor.fields import RichTextField



class Author(models.Model):
    name = models.CharField(max_length=225)
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Category(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title
    
class Post(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    description = RichTextField()
    categories = models.ManyToManyField("posts.Category")
    time_to_read = models.CharField(max_length=128)
    featured_image = models.ImageField(upload_to="posts/")
    is_draft = models.BooleanField(default=False)

    author = models.ForeignKey("posts.Author", on_delete=models.CASCADE)
    published_date = models.DateField()
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from posts.models import Post

class PostForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label="Tags (Comma separated)")


    class Meta:
        model = Post
        exclude = ('author', 'published_date', 'is_deleted', 'categories')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input'}),
            'short_description': forms.Textarea(attrs={'class': 'input'}),
            'time_to_read': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'editor'}),
        }

        error_messages = {
            "title": {
                "required": "Title field is required"
            },
            "short_description": {
                "required": "Short description field is required"
            },
            "description": {
                "required": "Description field is required"
            },
            "time_to_read": {
                "required": "Time to read field is required"
            },
            "featured_image": {
                "required": "Featured image field is required"
            },
            "is_draft": {
                "required": "Is draft field is required"
            },
            "tags": {
                "required": "Tags field is required"
            }
        }

posts/views.py
import datetime
import json

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from posts.forms import PostForm
from posts.models import Author, Category, Post
from main.functions import generate_form_errors, paginate_instances
from main.decorators import allow_self


@login_required(login_url="/users/login/")
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():

            tags = form.cleaned_data["tags"]
            if not Author.objects.filter(user=request.user).exists():
                name = Author.objects.create(user=request.user, name=request.user.username)
            else:
                author = request.user.author
            instance = form.save(commit = False)
            instance.published_date = datetime.date.today()
            instance.author = author
            instance.save()

            tags_list = tags.split(',')
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.categories.add(category)

            response_date = {
                "message": "Successfully post created",
                "title": "Successfully created",
                "status": "success",
                "redirect": "yes",
                "redirect_url": "/"
            }

        else:
            error_message = generate_form_errors(form)
            response_date = {
                "message": str(error_message),
                "title": "Form validation error",
                "status": "error",
                "stable": "yes"
            }
        
        return HttpResponse(json.dumps(response_date), content_type="application/json")

    else: 
        data = {
            "title" : "hello",
            "description" : "hello",
            "short_description" : "hello",
            "time_to_read" : "8 minutes",
            "tags" : "technology, coding, programming"

        }
        form = PostForm(initial=data)
        context = {
            "title": "Create new post",
            "form" : form
        }
        return render(request, "posts/create.html", context=context)

@login_required(login_url="/users/login/")
def my_posts(request):
    posts = Post.objects.filter(author__user=request.user, is_deleted=False)
    instances = paginate_instances(request, posts, per_page=5)
    context = {
        "title" : "My Posts",
        "instances":instances
    }
    return render(request, "posts/my-posts.html", context=context)

@login_required(login_url="/users/login/")
@allow_self
def delete_post(request, id):
    instance = get_object_or_404(Post, id=id)
    instance.is_deleted = True
    instance.save()

    respose_data ={
        "title" : "Successfully deleted",
        "message": "Post deleted successfully",
        "status" : "success"
    }

    return HttpResponse(json.dumps(respose_data), content_type = "application/json")


@login_required(login_url="/users/login/")
@allow_self
def draft_post(request, id):
    instance = get_object_or_404(Post, id=id)
    instance.is_draft = not instance.is_draft
    instance.save()

    respose_data ={
        "title" : "Successfully changed",
        "message": "Post updated successfully",
        "status" : "success"
    }

    return HttpResponse(json.dumps(respose_data), content_type = "application/json")

@login_required(login_url="/users/login/")
@allow_self
def edit_post(request, id):
    
    instance = get_object_or_404(Post, id=id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():

            tags = form.cleaned_data["tags"]

            instance = form.save(commit = False)
            instance.save()

            instance.categories.clear()

            tags_list = tags.split(',')
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.categories.add(category)

            response_date = {
                "message": "Successfully post edited",
                "title": "Successfully Edited",
                "status": "success",
                "redirect": "yes",
                "redirect_url": "/"
            }

        else:
            error_message = generate_form_errors(form)
            response_date = {
                "message": str(error_message),
                "title": "Form validation error",
                "status": "error",
                "stable": "yes"
            }
        
        return HttpResponse(json.dumps(response_date), content_type="application/json")

    else: 
        category_string = ""
        for category in instance.categories.all():
            category_string += f"{category.title},"

        form = PostForm(instance=instance, initial={"tags":category_string[-1]})

        context = {
            "title": "Edit your post",
            "form" : form
        }
        return render(request, "posts/create.html", context=context)

def post(request, id):
    instance = get_object_or_404(Post, id=id)
    context = {
        'instance': instance
    }
    return render(request, 'web/post.html', context)

templates/posts/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <section id="edit-post-home">
            <section class="wrapper">   
                {% include 'web/includes/header.html' %}
                <section class="spotlight">
                    <h3>{{title}}</h3>
                    <form action="" method="post" enctype="multipart/form-data" class="ajax redirect">
                        {% csrf_token %}
                            <div class="form-field">
                                <label for="{{form.title.id_for_label}}" class="subheads" >
                                    {{form.title.label}}
                                </label>
                                {{form.title}}
                            </div>
                            <div class="form-field">
                                <label class="subheads" for="{{ form.description.id_for_label }}">
                                    Content
                                </label>
                                <div class="description">
                                    <div class="editor" data-field-id="id_description" style="display: inline-block;">
                                        {{ form.description }}
                                    </div>
                                </div>
                            </div>
                            
                            <div class="form-field">
                                <label class="subheads" for="{{form.short_description.id_for_label}}">
                                   {{form.short_description.label}}
                                </label>
                                {{form.short_description}}
                            </div>
                            <div class="form-field">
                                <label class="subheads" for="{{form.tags.id_for_label}}">
                                    {{form.tags.label}}
                                </label>
                                {{form.tags}}
                            </div>
                            <div class="form-field">
                                <label for="{{form.time_to_read.id_for_label}}" class="subheads" >
                                    {{form.time_to_read.label}}
                                </label>
                                {{form.time_to_read}}
                            </div>
                            <div class="form-field">
                                <label for="{{form.featured_image.id_featured_image}}" class="subheads" >
                                    {{form.featured_image.label}}
                                </label>
                                {{form.featured_image}}
                            </div>
                            <div class="form-field"></div>
                                <label class="checkbox">
                                    {{form.is_draft}}
                                    {{form.is_draft.label}}
                                </label>
                            </div>
                            <div class="form-field">
                                <input type="submit" value="Submit" />
                            </div>
                    </form>
                    {{form.media}}
                </section>
            </section>
        </section>
        <!-- <script src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script> -->
        <!-- <script src="{% static 'js/ckeditor.js"></script> -->
        <script>ClassicEditor
            .create( document.querySelector( '.editor' ), {
                
                licenseKey: '',
                
                
                
            } )
            .then( editor => {
                window.editor = editor;
        
                
                
                
            } )
            .catch( error => {
                console.error( 'Oops, something went wrong!' );
                console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
                console.warn( 'Build id: fbn1rnj89y5k-nohdljl880ze' );
                console.error( error );
            } );
        </script>

    {% endblock %}

templates/posts/my-posts.html
{% extends 'base.html'%}
{% load static %}
{% load paginator_tags %}
{% block content%}
        <section id="my-posts-home">
            <section class="wrapper">                
                {% include 'web/includes/header.html' %}
                <section class="spotlight">
                    <h3>
                        My Posts
                    </h3>
                    <ul class="posts">
                        {% for instance in instances %}
                            <li class="post">
                                <div class="top">
                                    <h5 class="title">
                                        {{instance.title}}
                                    </h5>
                                    <div class="buttons">
                                        <a 
                                        href="{% url 'posts:delete_post' id=instance.id %}" 
                                        class="danger action-button reload"
                                        data-text="Are you sure want to remove this post. You can't undo this action." 
                                        data-title="Confirm Delete!"
                                        title="Delete!"
                                    >
                                            <img src="{% static 'images/icons/delete.svg' %}" alt="Delete" />
                                        </a>
                                        <a href="{% url 'posts:edit_post' id=instance.id %}" class="warning">
                                            <img src="{% static 'images/icons/pencil.svg' %}" alt="Edit" />
                                        </a>
                                        <a 
                                            href="{% url 'posts:draft_post' id=instance.id %}" 
                                            class="{% if instance.is_draft %}success{% else %}danger{% endif %} action-button reload"
                                            data-text="Are you sure want to update this post" 
                                            data-title="Confirm Status!"
                                            title="Draft"
                                        >
                                            <img src="{% static 'images/icons/sheet.svg' %}" alt="Edit" />
                                        </a>
                                    </div>
                                </div>
                                <p class="description">
                                    {{instance.short_description}}
                                </p>
                                <div class="bottom">
                                    <a href="{% url 'posts:post' instance.id %}" class="view">
                                        View
                                        <span>
                                            <img src="{% static 'images/icons/up-arrow.svg' %}" alt="Arrow">
                                        </span>
                                    </a>
                                    <p class="date">
                                        {{ instance.published_date|date:"d M Y" }}
                                    </p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </section>
                {% load_pagination instances %}
            </section>
        </section>
{% endblock %}