blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
    path('posts/', include("posts.urls", namespace="posts"))
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

posts/urls.py
from django.urls import path, include
from posts import views

app_name = "posts"

urlpatterns = [
    path("create/", views.create_post, name = "create_post"),
    path("my-posts/", views.my_posts, name = "my_posts"),
    path("delete/<int:id>/", views.delete_post, name = "delete_post"),
    path("edit/<int:id>/", views.edit_post, name = "edit_post"),
    path("draft/<int:id>/", views.draft_post, name = "draft_post"),
    path("<int:id>/", views.post, name = "post"),
]

users/urls.py
from django.urls import path, include
from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name = "login"),
    path("logout/", views.logout, name = "logout"),
    path("signup/", views.signup, name = "signup")
]

web/urls.py
from django.urls import path, include
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:id>/", views.post, name = "post"),
]

templates/web/includes/header.html
{% load static %}

<header>
    <h1>
        <a href="{% url 'web:index' %}">
            <img
                src="{% static 'images/icons/blog-logo.svg' %}"
                alt="Logo"
            />
        </a>
    </h1>
    <div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'posts:create_post' %}" class="login my-posts">Create</a>
            <a href="{% url 'posts:my_posts' %}" class="login my-posts">My posts</a>
            <a href="{% url 'users:logout' %}" class="login"> Logout </a>
        {% else %}
            <a href="{% url 'users:login' %}" class="login">Login</a>
        {% endif %}
    <div>
    <div id="hamburger-icon">
        <img
            src="{% static 'images/icons/hamburger.svg' %}"
            alt="Hamburger"
        />
    </div>
</header>

templates/web/includes/pagination.html
{% load static %}
{% load paginator_tags %}
{% if instances.has_other_pages %}
    <div class="pagination">
        {% if instances.has_previous %}
            {% change_params instances.previous_page_number as prev_url %}
                <a href="{{prev_url}}" class="prev">
                    <span class="arrow">
                    <img
                        src="{% static 'images/icons/arrow.svg' %}"
                        alt="Arrow"
                    />
                    </span>
                    Previous
                </a>
        {% else %}
            <div class="prev disabled">
                <span class="arrow">
                    <img
                        src="{% static 'images/icons/arrow.svg' %}"
                        alt="Arrow"
                    />
                </span>
                Previous
            </div>
        {% endif %}
            <div class="pages">
                {% get_elided_page_range instances.paginator instances.number as page_range%}
                    {% for i in page_range %}
                        {% if instances.number == i %}
                            <span class="active"> {{i}} </span>
                        {% else %}
                            {% change_params i as current_url %}
                                <a href="{{current_url}}"> {{i}} </a>
                        {% endif %}
                    {% endfor %}
            </div>
        {% if instances.has_next %}
            {% change_params instances.next_page_number as next_url %}
                <a href="{{next_url}}" class="next">
                    Next
                    <span class="arrow">
                        <img
                            src="{% static 'images/icons/arrow.svg' %}"
                            alt="Arrow"
                        />
                    </span>
                </a>
        {% else %}
            <a class="next disabled">
                Next
                    <span class="arrow">
                        <img
                            src="{% static 'images/icons/arrow.svg' %}"
                            alt="Arrow"
                        />
                    </span>
            </a>
        {% endif %}
    </div>
{% endif %}