blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
    path('posts/', include("posts.urls", namespace="posts"))
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

posts/urls.py
from django.urls import path, include
from posts import views

app_name = "posts"

urlpatterns = [
    path("create/", views.create_post, name = "create_post"),
    path("my-posts/", views.my_posts, name = "my_posts"),
    path("delete/<int:id>/", views.delete_post, name = "delete_post"),
    path("edit/<int:id>/", views.edit_post, name = "edit_post"),
    path("draft/<int:id>/", views.draft_post, name = "draft_post"),
    path("<int:id>/", views.post, name = "post"),
]

web/urls.py
from django.urls import path, include
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:id>/", views.post, name = "post"),
]

posts/models.py
from django.db import models
from ckeditor.fields import RichTextField



class Author(models.Model):
    name = models.CharField(max_length=225)
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Category(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title
    
class Post(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    description = RichTextField()
    categories = models.ManyToManyField("posts.Category")
    time_to_read = models.CharField(max_length=128)
    featured_image = models.ImageField(upload_to="posts/")
    is_draft = models.BooleanField(default=False)

    author = models.ForeignKey("posts.Author", on_delete=models.CASCADE)
    published_date = models.DateField()
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from posts.models import Post

class PostForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), label="Tags (Comma separated)")


    class Meta:
        model = Post
        exclude = ('author', 'published_date', 'is_deleted', 'categories')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input'}),
            'short_description': forms.Textarea(attrs={'class': 'input'}),
            'time_to_read': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'editor'}),
        }

        error_messages = {
            "title": {
                "required": "Title field is required"
            },
            "short_description": {
                "required": "Short description field is required"
            },
            "description": {
                "required": "Description field is required"
            },
            "time_to_read": {
                "required": "Time to read field is required"
            },
            "featured_image": {
                "required": "Featured image field is required"
            },
            "is_draft": {
                "required": "Is draft field is required"
            },
            "tags": {
                "required": "Tags field is required"
            }
        }

posts/views.py
import datetime
import json

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from posts.forms import PostForm
from posts.models import Author, Category, Post
from main.functions import generate_form_errors, paginate_instances
from main.decorators import allow_self


@login_required(login_url="/users/login/")
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():

            tags = form.cleaned_data["tags"]
            if not Author.objects.filter(user=request.user).exists():
                name = Author.objects.create(user=request.user, name=request.user.username)
            else:
                author = request.user.author
            instance = form.save(commit = False)
            instance.published_date = datetime.date.today()
            instance.author = author
            instance.save()

            tags_list = tags.split(',')
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.categories.add(category)

            response_date = {
                "message": "Successfully post created",
                "title": "Successfully created",
                "status": "success",
                "redirect": "yes",
                "redirect_url": "/"
            }

        else:
            error_message = generate_form_errors(form)
            response_date = {
                "message": str(error_message),
                "title": "Form validation error",
                "status": "error",
                "stable": "yes"
            }
        
        return HttpResponse(json.dumps(response_date), content_type="application/json")

    else: 
        data = {
            "title" : "hello",
            "description" : "hello",
            "short_description" : "hello",
            "time_to_read" : "8 minutes",
            "tags" : "technology, coding, programming"

        }
        form = PostForm(initial=data)
        context = {
            "title": "Create new post",
            "form" : form
        }
        return render(request, "posts/create.html", context=context)

@login_required(login_url="/users/login/")
def my_posts(request):
    posts = Post.objects.filter(author__user=request.user, is_deleted=False)
    instances = paginate_instances(request, posts, per_page=5)
    context = {
        "title" : "My Posts",
        "instances":instances
    }
    return render(request, "posts/my-posts.html", context=context)

@login_required(login_url="/users/login/")
@allow_self
def delete_post(request, id):
    instance = get_object_or_404(Post, id=id)
    instance.is_deleted = True
    instance.save()

    respose_data ={
        "title" : "Successfully deleted",
        "message": "Post deleted successfully",
        "status" : "success"
    }

    return HttpResponse(json.dumps(respose_data), content_type = "application/json")


@login_required(login_url="/users/login/")
@allow_self
def draft_post(request, id):
    instance = get_object_or_404(Post, id=id)
    instance.is_draft = not instance.is_draft
    instance.save()

    respose_data ={
        "title" : "Successfully changed",
        "message": "Post updated successfully",
        "status" : "success"
    }

    return HttpResponse(json.dumps(respose_data), content_type = "application/json")

@login_required(login_url="/users/login/")
@allow_self
def edit_post(request, id):
    
    instance = get_object_or_404(Post, id=id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():

            tags = form.cleaned_data["tags"]

            instance = form.save(commit = False)
            instance.save()

            instance.categories.clear()

            tags_list = tags.split(',')
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.categories.add(category)

            response_date = {
                "message": "Successfully post edited",
                "title": "Successfully Edited",
                "status": "success",
                "redirect": "yes",
                "redirect_url": "/"
            }

        else:
            error_message = generate_form_errors(form)
            response_date = {
                "message": str(error_message),
                "title": "Form validation error",
                "status": "error",
                "stable": "yes"
            }
        
        return HttpResponse(json.dumps(response_date), content_type="application/json")

    else: 
        category_string = ""
        for category in instance.categories.all():
            category_string += f"{category.title},"

        form = PostForm(instance=instance, initial={"tags":category_string[-1]})

        context = {
            "title": "Edit your post",
            "form" : form
        }
        return render(request, "posts/create.html", context=context)

def post(request, id):
    instance = get_object_or_404(Post, id=id)
    context = {
        'instance': instance
    }
    return render(request, 'web/post.html', context)

templates/web/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load paginator_tags %}

    <section id="home">
        <section class="wrapper">
            {% include 'web/includes/header.html' %}
            <section class="spotlight">
                <h3>Posts</h3>
                <div class="all-posts">
                    <div class="post-section">
                        <ul class="posts">
                            {% for post in instances %}
                            <li>
                                <a href="{% url 'web:post' id=post.id %}">
                                    <div class="blog-image">
                                        <img
                                            src="{{post.featured_image.url}}"
                                            alt="Blog"
                                        />
                                    </div>
                                    <div class="details">
                                        <div class="date">
                                            <h4 class="name">{{post.author.name}}</h4>
                                            <div class="round"></div>
                                            <span> {{post.published_date|date:"d/m/Y"}}</span>
                                        </div>
                                        <h3 class="head">
                                            {{post.title|title|default:"Title"}}
                                        </h3>
                                        <h6>Comments True</h6>
                                        <p class="description">
                                        {{post.short_description|safe| striptags | truncatewords:30}}
                                        </p>
                                    </div>
                                </a>
                                <div class="bottom">
                                    {% for tag in post.categories.all %}
                                    <a href="#" class="design {% cycle 'one' 'two' 'three' %}" > {{tag.title}} </a>
                                    {% endfor %}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>

                        {% load_pagination instances %}
    
                    </div>
                    <div class="filter-section" id="hamburger-menu">
                        <form action="">
                            <input type="text" name="q" placeholder="Search anything..." />
                            <p class="filter-head">Sort by</p>
                            <div class="filter">
                                <label class="radio">
                                    <input
                                        type="radio"
                                        name="sort"
                                        value="title-asc"
                                    />
                                    <span class="radio"></span>
                                    <span class="label">Title ordered by Asc</span>
                                </label>
                                <label class="radio">
                                    <input
                                        type="radio"
                                        name="sort"
                                        value="title-desc"
                                    />
                                    <span class="radio"></span>
                                    <span class="label">Title ordered by Desc</span>
                                </label>
                                <label class="radio">
                                    <input
                                        type="radio"
                                        name="sort"
                                        value="date-asc"
                                    />
                                    <span class="radio"></span>
                                    <span class="label"
                                        >Order By Date added Asc</span
                                    >
                                </label>
                                <label class="radio">
                                    <input
                                        type="radio"
                                        name="sort"
                                        value="date-desc"
                                    />
                                    <span class="radio"></span>
                                    <span class="label"
                                        >Order By Date added Desc</span
                                    >
                                </label>
                            </div>
                            <p class="filter-head">Categories</p>
                            <div class="filter">
                                {% for category in categories %}
                                <label class="checkbox">
                                    <input type="checkbox" value="{{category.id}}" name="category" />
                                    <span class="label">{{category.title}}</span>
                                </label>
                                {% endfor %}
                            </div>
                            <p class="filter-head">Authors</p>
                            <div class="filter">
                            {% for author in authors %}
                                <label class="checkbox">
                                    <input type="checkbox" value="{{author.id}}" name="author" />
                                    <span class="label">{{author.name}}</span>
                                </label>
                            {% endfor %}
                            </div>
                            <input type="submit" value="Filter" />
                        </form>
                    </div>
                </div>
            </section>
            <div id="overlay"></div>
            <div id="close">
                <img src="{% static 'images/icons/close.svg' %}" alt="" />
            </div>
        </section>
    </section>

{% endblock%}

templates/web/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section id="single-page-home">
        <section class="wrapper">         
            {% include 'web/includes/header.html' %}
            <section class="single-page-spotlight">
                <div class="blog-category">
                    {% for category in instance.categories.all %}
                    <span class="category">
                        {{category.title}}
                    </span>
                    {% endfor %}
                    <span class="read">
                        <span class="clock">
                            <img src="{% static 'images/icons/clock.svg' %}" alt="Clock" />
                        </span>
                        {{instance.time_to_read}}
                    </span>
                </div>
                <h3 class="title">
                    {{instance.title}}
                </h3>
                <p class="description">
                    {{instance.short_description}}
                </p>
                <div class="post-thumbnail">
                    <img src="{{instance.featured_image.url}}" alt="Post-thumbnail" >
                </div>
                <div class="details">
                    <span class="published">
                        <p class="written">
                            Written by
                        </p>
                        <p class="name">
                            {{instance.author}}
                        </p>
                    </span>
                    <span class="published">
                        <p class="written">
                            Published on
                        </p>
                        <p class="name">
                        {{instance.published_date}}
                        </p>
                    </span>
                    <ul class="social">
                        <li>
                            <a href="#" class="copy-link">
                                <span class="link">
                                    <img src="{% static 'images/icons/copy-link.svg' %}" alt="Copy-link" />
                                </span>
                                Copy link
                            </a>
                        </li>
                        <li class="social-media">
                            <a href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}&text={{ post.title|urlencode }}" target="_blank">
                                <img src="{% static 'images/icons/X.svg' %}" alt="Twitter (X)" />
                            </a>
                        </li>
                        
                        <li class="social-media">
                            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">
                                <img src="{% static 'images/icons/facebook.svg' %}" alt="Facebook" />
                            </a>
                        </li>
                        
                        <li class="social-media">
                            <a href="https://api.whatsapp.com/send/?text={{ request.build_absolute_uri }}" target="_blank">
                                <img src="{% static 'images/icons/whatsapp.svg' %}" alt="WhatsApp" />
                            </a>
                        </li>
                    </ul>
                </div>
                <p class="detailed-description">
                    {{instance.description|safe}}
                </p>
                </section>
        </section>
    </section>

{% endblock %}