blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
    path('posts/', include("posts.urls", namespace="posts"))
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

users/urls.py
from django.urls import path, include
from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name = "login"),
    path("logout/", views.logout, name = "logout"),
    path("signup/", views.signup, name = "signup")
]

web/urls.py
from django.urls import path, include
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:id>/", views.post, name = "post"),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username','password']
        widgets = {
            'password': forms.widgets.PasswordInput(),
        }

users/views.py
from django.shortcuts import render, reverse

from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User

from users.forms import UserForm
from main.functions import generate_form_errors
from posts.models import Author


def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect("/")
            else:
                context = {
                    "title" : "Login",
                    "error" : True,
                    "message" : "Invalid username or password"
                }
                return render(request, "users/login.html", context = context)
        else: 
            context = {
            "title" : "Login",
            "error" : True,
            "message" : "Invalid username or password"
        }
        return render(request, "users/login.html", context = context)
    else:
        context = {
            "title" : "Login"
        }
        return render(request, "users/login.html", context = context)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("web:index"))

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username=instance.username,
                password=instance.password,
                email=instance.email,
                first_name=instance.first_name,
                last_name=instance.last_name
            )

            Author.objects.create(
                name = instance.first_name,
                user = user
            )
            
            user = authenticate(request, username=instance.username, password=instance.password)
            auth_login(request, user)

            return HttpResponseRedirect(reverse("web:index"))
        else:
            message = generate_form_errors(form)
            form = UserForm()
            context = {
            "title" : "Signup",
            "error" : True,
            "message" : message,
            "form" : form,
        }
        return render(request, "users/signup.html", context = context)
    else:
        form = UserForm()
        context = {
            "title" : "Signup",
            "form" : form,
        }
        return render(request, "users/signup.html", context = context)
    

templates/users/auth_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/auth-style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <section class="container">

        {% block content %} 

        {% endblock %}
    
    </section>
</body>
</html>

templates/users/login.html
{% extends "users/auth_base.html" %}
    {% load static %}
    {% block content %}
            <section class="form_container">
                <div class="top">
                    <h5>Login Page</h5>
                </div>
                <div class="bottom">
                    <form action="" method="post" >
                        {% csrf_token %}
                        <div class="input_container">
                            <label for="id_username"> Username </label>
                            <input id="id_username" name="username" type="text" />
                        </div>
                        <div class="input_container">
                            <label for="id_password"> Password </label>
                            <input id="id_password" name="password" type="password" />
                        </div>
                        <div class="submit_container">
                            {% if error %}
                            <p class="error-message">{{message}}</p>
                            {% endif %}
                            <button type="submit">Log in</button>

                            <a href="{% url 'users:signup' %}">Create Account</a>
                        </div>
                    </form>
                </div>
            </section>
    {% endblock %}

templates/users/signup.html
{% extends "users/auth_base.html" %}
    {% load static %}
    {% block content %}
        <section class="form_container">
            <div class="top">
                <h5>SignUp Page</h5>
            </div>
            <div class="bottom">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="input_container">
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                        </label>
                        {{ field}}
                    </div>
                    {% endfor %}
                    
                    <div class="submit_container">
                        {% if error %}
                        <p class="error-message">
                            {{message}}
                        </p>
                        {% endif %}
                        <button type="submit">Create Account</button>

                        <a href="{% url 'users:login' %}">Login</a>
                    </div>
                </form>
            </div>
        </section>
    {% endblock %}